//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoupRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int IdConnection { get; set; }
        public string IdUser { get; set; }
        public System.DateTime DateConnection { get; set; }
    
        public virtual UserYoup UserYoup { get; set; }
    }
}
