//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoupRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public Events()
        {
            this.Cards = new HashSet<Cards>();
            this.EventComments = new HashSet<EventComments>();
            this.Ratings = new HashSet<Ratings>();
            this.Threads = new HashSet<Threads>();
            this.Users1 = new HashSet<Users>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public int Slots { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<short> Public { get; set; }
        public string Description { get; set; }
        public string UserId { get; set; }
        public int ThemeId { get; set; }
        public string Address { get; set; }
        public Nullable<float> Lattitude { get; set; }
        public Nullable<float> Longitude { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual ICollection<Cards> Cards { get; set; }
        public virtual ICollection<EventComments> EventComments { get; set; }
        public virtual Themes Themes { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Ratings> Ratings { get; set; }
        public virtual ICollection<Threads> Threads { get; set; }
        public virtual ICollection<Users> Users1 { get; set; }
    }
}
