//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoupRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Cards = new HashSet<Card>();
            this.EventComments = new HashSet<EventComment>();
            this.Ratings = new HashSet<Rating>();
            this.Threads = new HashSet<Thread>();
            this.Users = new HashSet<User>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public int Slots { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<short> Public { get; set; }
        public string Description { get; set; }
        public string UserId { get; set; }
        public int ThemeId { get; set; }
        public string Address { get; set; }
        public Nullable<float> Lattitude { get; set; }
        public Nullable<float> Longitude { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Card> Cards { get; set; }
        public virtual Theme Theme { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<EventComment> EventComments { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Thread> Threads { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
