//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoupRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Cards = new HashSet<Card>();
            this.EventComments = new HashSet<EventComment>();
            this.Ratings = new HashSet<Rating>();
            this.Threads = new HashSet<Thread>();
            this.UserYoups = new HashSet<UserYoup>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public int Slots { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<short> Public { get; set; }
        public string Description { get; set; }
        public string UserId { get; set; }
        public int ThemeId { get; set; }
        public string Address { get; set; }
        public Nullable<float> Lattitude { get; set; }
        public Nullable<float> Longitude { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Card> Cards { get; set; }
        public virtual ICollection<EventComment> EventComments { get; set; }
        public virtual Theme Theme { get; set; }
        public virtual UserYoup UserYoup { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Thread> Threads { get; set; }
        public virtual ICollection<UserYoup> UserYoups { get; set; }
    }
}
