//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoupRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeatMap
    {
        public int IdHeatMap { get; set; }
        public int HeatMapX { get; set; }
        public int HeatMapY { get; set; }
        public System.DateTime DateHeatMap { get; set; }
        public int IdPage { get; set; }
        public int Width { get; set; }
    }
}
