//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoupRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeatMap
    {
        public int IdHeatMap { get; set; }
        public int HeatMapX { get; set; }
        public int HeatMapY { get; set; }
        public System.DateTime DateHeatMap { get; set; }
        public int IdPage { get; set; }
        public int Width { get; set; }
    
        public virtual Page Page { get; set; }
    }
}
