//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoupRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.BlogComments = new HashSet<BlogComment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> Visibility { get; set; }
        public int ThemeId { get; set; }
        public int BlogId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string ImageUrl { get; set; }
        public int NombreLike { get; set; }
    
        public virtual ICollection<BlogComment> BlogComments { get; set; }
        public virtual Blog Blog { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
