//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoupRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Themes
    {
        public Themes()
        {
            this.Events = new HashSet<Events>();
            this.Posts = new HashSet<Posts>();
            this.Themes1 = new HashSet<Themes>();
            this.Threads = new HashSet<Threads>();
            this.Users = new HashSet<Users>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ThemeId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual ICollection<Events> Events { get; set; }
        public virtual ICollection<Posts> Posts { get; set; }
        public virtual ICollection<Themes> Themes1 { get; set; }
        public virtual Themes Themes2 { get; set; }
        public virtual ICollection<Threads> Threads { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
