//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoupRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thread
    {
        public Thread()
        {
            this.Favorites = new HashSet<Favorite>();
            this.Messages = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<short> IsSharable { get; set; }
        public int ThemeId { get; set; }
        public string EventId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
