//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoupRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserYoup
    {
        public UserYoup()
        {
            this.BlogComments = new HashSet<BlogComment>();
            this.Blogs = new HashSet<Blog>();
            this.Cards = new HashSet<Card>();
            this.Connections = new HashSet<Connection>();
            this.EventComments = new HashSet<EventComment>();
            this.Events = new HashSet<Event>();
            this.Favorites = new HashSet<Favorite>();
            this.Messages = new HashSet<Message>();
            this.Photos = new HashSet<Photo>();
            this.Ratings = new HashSet<Rating>();
            this.UserHistorys = new HashSet<UserHistory>();
            this.Events1 = new HashSet<Event>();
            this.Themes = new HashSet<Theme>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string GuidFacebook { get; set; }
        public Nullable<short> IsActive { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Address { get; set; }
        public int RankId { get; set; }
        public int RoleId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string ResetPasswordToken { get; set; }
        public Nullable<System.DateTime> ResetTokenSentAt { get; set; }
    
        public virtual ICollection<BlogComment> BlogComments { get; set; }
        public virtual ICollection<Blog> Blogs { get; set; }
        public virtual ICollection<Card> Cards { get; set; }
        public virtual ICollection<Connection> Connections { get; set; }
        public virtual ICollection<EventComment> EventComments { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual Rank Rank { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<UserHistory> UserHistorys { get; set; }
        public virtual ICollection<Event> Events1 { get; set; }
        public virtual ICollection<Theme> Themes { get; set; }
    }
}
