//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoupRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.BlogComments = new HashSet<BlogComments>();
            this.Blogs = new HashSet<Blogs>();
            this.Cards = new HashSet<Cards>();
            this.EventComments = new HashSet<EventComments>();
            this.Events = new HashSet<Events>();
            this.Favorites = new HashSet<Favorites>();
            this.Messages = new HashSet<Messages>();
            this.Photos = new HashSet<Photos>();
            this.Ratings = new HashSet<Ratings>();
            this.Events1 = new HashSet<Events>();
            this.Themes = new HashSet<Themes>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string GuidFacebook { get; set; }
        public Nullable<short> IsActive { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Address { get; set; }
        public int RankId { get; set; }
        public int RoleId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual ICollection<BlogComments> BlogComments { get; set; }
        public virtual ICollection<Blogs> Blogs { get; set; }
        public virtual ICollection<Cards> Cards { get; set; }
        public virtual ICollection<EventComments> EventComments { get; set; }
        public virtual ICollection<Events> Events { get; set; }
        public virtual ICollection<Favorites> Favorites { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual ICollection<Photos> Photos { get; set; }
        public virtual Ranks Ranks { get; set; }
        public virtual ICollection<Ratings> Ratings { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<Events> Events1 { get; set; }
        public virtual ICollection<Themes> Themes { get; set; }
    }
}
