//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoupRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHistory
    {
        public int IdHistory { get; set; }
        public string IdUser { get; set; }
        public string Referer { get; set; }
        public System.DateTime DateHistory { get; set; }
        public string UserAgent { get; set; }
    
        public virtual User User { get; set; }
    }
}
