//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoupRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Blogs = new HashSet<Blog>();
            this.BlogComments = new HashSet<BlogComment>();
            this.Cards = new HashSet<Card>();
            this.Events = new HashSet<Event>();
            this.EventComments = new HashSet<EventComment>();
            this.Favorites = new HashSet<Favorite>();
            this.Messages = new HashSet<Message>();
            this.Photos = new HashSet<Photo>();
            this.Ratings = new HashSet<Rating>();
            this.Events1 = new HashSet<Event>();
            this.Themes = new HashSet<Theme>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string GuidFacebook { get; set; }
        public Nullable<short> IsActive { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Address { get; set; }
        public int RankId { get; set; }
        public int RoleId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual ICollection<Blog> Blogs { get; set; }
        public virtual ICollection<BlogComment> BlogComments { get; set; }
        public virtual ICollection<Card> Cards { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<EventComment> EventComments { get; set; }
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual Rank Rank { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Event> Events1 { get; set; }
        public virtual ICollection<Theme> Themes { get; set; }
    }
}
