//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoupRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YoupEntities : DbContext
    {
        public YoupEntities()
            : base("name=YoupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
            modelBuilder.Entity<Connection>().HasKey(t => new { t.IdConnection });
            modelBuilder.Entity<UserHistory>().HasKey(t => new { t.IdHistory });
            modelBuilder.Entity<HeatMap>().HasKey(t => new { t.IdHeatMap });
            modelBuilder.Entity<Page>().HasKey(t => new { t.IdPage });
        }
    
        public DbSet<BlogComment> BlogComments { get; set; }
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Card> Cards { get; set; }
        public DbSet<Connection> Connections { get; set; }
        public DbSet<EventComment> EventComments { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Favorite> Favorites { get; set; }
        public DbSet<HeatMap> HeatMaps { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<Page> Pages { get; set; }
        public DbSet<Photo> Photos { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<Rank> Ranks { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Theme> Themes { get; set; }
        public DbSet<Thread> Threads { get; set; }
        public DbSet<UserHistory> UserHistorys { get; set; }
        public DbSet<UserYoup> UserYoups { get; set; }
    }
}
