//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoupRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YoupEntities : DbContext
    {
        public YoupEntities()
            : base("name=YoupEntities")
        {
        }
        public YoupEntities(string connectionString)
            : base(connectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BlogComments> BlogComments { get; set; }
        public DbSet<Blogs> Blogs { get; set; }
        public DbSet<Cards> Cards { get; set; }
        public DbSet<EventComments> EventComments { get; set; }
        public DbSet<Events> Events { get; set; }
        public DbSet<Favorites> Favorites { get; set; }
        public DbSet<Messages> Messages { get; set; }
        public DbSet<Photos> Photos { get; set; }
        public DbSet<Posts> Posts { get; set; }
        public DbSet<Ranks> Ranks { get; set; }
        public DbSet<Ratings> Ratings { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Themes> Themes { get; set; }
        public DbSet<Threads> Threads { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
